[package]
name = "problemdetailsmapper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
problem_details = "0.6.0"
http = "1.1.0"
